.TH "include/defs.hpp" 3 "Thu Jan 29 2026 14:23:22" "AVR Bingo Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/defs.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBF_CPU\fP   (1000000UL)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define F_CPU   (1000000UL)"
set clock to 1MHz 
.SH "Author"
.PP 
Generated automatically by Doxygen for AVR Bingo Machine from the source code\&.
