.TH "include/Pin.hpp" 3 "Thu Jan 29 2026 14:23:22" "AVR Bingo Machine" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/Pin.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPin\fP"
.br
.RI "\fBPin\fP class\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPORTA_P\fP   (uint8_t*)(0x39)"
.br
.RI "Pointer to PORTA register in Attiny44a\&. "
.ti -1c
.RI "#define \fBPORTB_P\fP   (uint8_t*)(0x36)"
.br
.RI "Pointer to PORTB register in Attiny44a\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PORTA_P   (uint8_t*)(0x39)"

.PP
Pointer to PORTA register in Attiny44a\&. 
.SS "#define PORTB_P   (uint8_t*)(0x36)"

.PP
Pointer to PORTB register in Attiny44a\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for AVR Bingo Machine from the source code\&.
